@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Apr 22 16:31:07 +0200 2025
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim asynchronous_synchronous_reset_tb_behav -key {Behavioral:sim_1:Functional:asynchronous_synchronous_reset_tb} -tclbatch asynchronous_synchronous_reset_tb.tcl -log simulate.log"
call xsim  asynchronous_synchronous_reset_tb_behav -key {Behavioral:sim_1:Functional:asynchronous_synchronous_reset_tb} -tclbatch asynchronous_synchronous_reset_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
